# Para nombrar las tareas o el conjunto de tareas que vamos a estar ejecutando
name: CI

# On sirve para decirle en que evento se v치 ejecutar
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Los jobs son una serie de pasos que nosotros queremos que ejecute este programa
  build:
    # The type of runner that the job will run on
    env:
      # Ac치 defino las variables de entorno por ejemplo Definimos una variable de entorno que contendr치 la versi칩n de Node.js que deseamos utilizar
      # NODE_VERSION: "14.x"
      platform: aws
      region: us-east-1
      account: 123456789012

      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        # Comando para mostrar un mensaje en la consola
        run: echo "Hello, world!"

      - name: "Mostrando variables de entorno"
        # if: ${{env.platform == 'azure'}}
        run: |
          echo "Esto es el valor de Platform: ${{env.platform}}"
          echo "Esto es el valor de Region: ${{env.region}}"
          echo "Esto es el valor de Account: ${{env.account}}"

          echo "Esto es el valor de Username: ${{secrets.USERNAME}}"
          echo "Esto es el valor de Password: ${{secrets.PASSWORD}}"

          echo "Esta es una variable guardada ${{vars.project_version}}"

      - name: "Mostrando valores solo si el usuario y password son correctos"
        if: ${{ env.username != '' && env.password != '' }}
        run: |
          echo "Usuario y Password correctos"

      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{toJSON(github.event)}}"
          echo "GITHUB_ACTOR: ${{github.actor}}"
          echo "Nombre del repositorio: ${{github.repository}}"

  other:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Mostrar mensaje"
        run: echo "Otro mensaje"
