# Para nombrar las tareas o el conjunto de tareas que vamos a estar ejecutando
name: CI

# On sirve para decirle en que evento se vá ejecutar
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Los jobs son una serie de pasos que nosotros queremos que ejecute este programa
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        # Comando para mostrar un mensaje en la consola
        run: echo "Hello, world!"
